
version: '3'

services:
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh node index.js
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports:
    - "3000:3000"
    networks: 
      - app-net
    depends_on:
      - db
      
  db:
    container_name: db
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true  
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/.data:/var/lib/mysql
    networks: 
      - app-net

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on: 
      - node

networks: 
  app-net:
    driver: bridge